#!/bin/sh

set -fuxe

echo "Checking Nexus SSL Keystore directory"
mkdir -p "$NEXUS_DATA/etc/ssl"
cd "$NEXUS_DATA/etc/ssl" || exit 1
if [ ! -f 'keystore.jks' ];
then
  keytool \
    -genkeypair \
    -keystore keystore.jks \
    -storepass password \
    -alias nexus.repo \
    -sigalg SHA256withRSA \
    -keyalg RSA \
    -keysize 2048 \
    -validity 5000 \
    -keypass password \
    -storetype pkcs12 \
    -dname 'CN=nexus.repo, OU=Sonatype, O=Sonatype, L=Unspecified, ST=Unspecified, C=US' \
    -ext 'SAN=IP:127.0.0.1,DNS:localhost'
fi

